### ISSUE TITLE
Dataset?

### ISSUE THREAD

**Issue by tphankr** [adigasu/SE_Despeckling#1]
Thank you for your nice code. How do we download a dataset to run train_SE.py. Thank you.

**Comment by adigasu** [comment]
Hi,

Please find the dataset links below:
1) [Dataset1](https://people.duke.edu/~sf59/Fang_TMI_2013.htm)
2) [Dataset2](https://people.duke.edu/~sf59/Fang_BOE_2012.htm)

For more details, please check out the experiments section in the [paper](http://web2py.iiit.ac.in/research_centres/publications/download/inproceedings.pdf.b2c08820db3e1d98.53756b6573685f49435647495031385f53452e706466.pdf).
